### ISSUE TITLE
iOS 13, UITableViewCell: stop method of Burst animation not called

### ISSUE THREAD

**Issue by lpbas** [piemonte/Burst#1]
Hello and thank you for this library! I'm using it in an app of mine, where I have a like button in posts, in a UITableViewCell.

When the button is pressed, the explode animation never stops. When debugging, if I create breakpoints at the dispatch blocks, then the methods get called normally and the animation stops, but without breakpoints, the animation never stops.

Do you have any idea how to work around this?

**Comment by piemonte** [comment]
hey @L4grange thanks for the project interest. i think the stop method just needs to be dispatched on the main queue. can take a look.

**Comment by lpbas** [comment]
Thank you @piemonte ! I've tried it on my project, since I suspected the same, but I had no luck. Please test it yourself as well, maybe I missed something.

If you have any other ideas, please let me know

**Comment by piemonte** [comment]
ah, it must just be some reference holding onto old emitter layers. stop maybe called on the new layers but no longer has a reference to the old ones. i can add a proper deinit but also a reset method. hopefully that'll do the trick.

**Comment by lpbas** [comment]
Thank you! Let me know when you want me to download a newer commit and test it.

**Comment by piemonte** [comment]
@L4grange i don't have a means of reproducing the error you've been seeing but landed changes that should address this. if you can test, would appreciate it.
